### ISSUE TITLE
any examples to use Cache?

### ISSUE THREAD

**Issue by hazho** [coleifer/micawber#103]
guys; kindly provide us an example of view cache or in-template cache regarding to the documentation [link ](https://micawber.readthedocs.io/en/latest/api.html#module-micawber.cache)

**Comment by coleifer** [comment]
The `Cache` instance is used when bootstrapping a provider-registry.

```python

from micawber import Cache, bootstrap_oembed

cache = Cache()  # Simple in-memory cache.
pr = bootstrap_oembed(cache=cache)
```
