### ISSUE TITLE
How to bootstrap Iframely?

### ISSUE THREAD

**Issue by iparamonau** [coleifer/micawber#41]
Hi Charles, this is a separate ticket to continue [this discussion](https://github.com/coleifer/micawber/issues/38#issuecomment-68622593).

We added the description of Iframely's approach to providers here: https://iframely.com/docs/providers. 

Though our preference would be to bootstrap for all URLs as Iframely can generate summary cards, handle link shorteners, detect direct image links, etc. 

Another issue is the API endpoint address:

 - cloud oEmbed API is at http://iframe.ly/api/oembed?url=...&api_key=....
 - however, Iframely can also be self-hosted and developers can have their own API endpoint address as the Iframely is [open-source](https://github.com/itteco/iframely)

Any suggestions?

**Comment by coleifer** [comment]
iframely is a bit different from the other providers, since it matches so many types of URLs. If someone wanted to use it, they would just register a single provider with a regex that matched any URL, and point it to your service. It would be straightforward.

**Comment by coleifer** [comment]
I don't plan on adding this feature myself, but interested users probably won't have much trouble getting iframely working. I am going to close this for now.

**Comment by iparamonau** [comment]
Ah, yes, I see. If  `Provider('...')` accepts API addresses with query strings in it, it should do the trick.

Thanks a lot. See - we didn't need a separate ticket :)

**Comment by coleifer** [comment]
Google will find this a lot more easily. Thanks for opening it.
