### ISSUE TITLE
eMonitor provider

### ISSUE THREAD

**Issue by Eibriel** [coleifer/micawber#42]
If you want to add my web service http://monitor.eibriel.com as a provider:

```
providers.register('http://monitor.eibriel.com/\S*', Provider('http://monitor.eibriel.com/api/job/oembed'))
```
Example: http://monitor.eibriel.com/54f317ef7ff6a915d864496a

Bests!

**Comment by coleifer** [comment]
Thanks I think I'll pass but if people are interested they can certainly add yours using the `register()` API.
