### ISSUE TITLE
Duration of videos not showing?

### ISSUE THREAD

**Issue by interneteur** [coleifer/micawber#48]
Hi, so I am following your example.  When I pull the json from 

micawber.bootstrap_basic().request('https://www.youtube.com/watch?v=M9taeyvPQzg')

It pulls all the info, but for some reason it does not pull the duration?

**Comment by coleifer** [comment]
> it does not pull the duration?

YouTube must not provide this information as part of it's OEmbed endpoint. Nothing really to do about it, certainly not a bug in micawber AFAICT.
