### ISSUE TITLE
Media with https

### ISSUE THREAD

**Issue by aledeg** [coleifer/micawber#61]
I am trying to embed that [video](http://www.dailymotion.com/video/x1apjif_une-arbalete-de-poche-fabriquee-manuellement_tv) in my [nikola](https://github.com/getnikola/nikola) blog post.

The video is embed in http no matter what configuration I use.
I tried both http and https with the following syntax:
```rst
# With http
.. media:: http://www.dailymotion.com/video/x1apjif_une-arbalete-de-poche-fabriquee-manuellement_tv

# With https
.. media:: https://www.dailymotion.com/video/x1apjif_une-arbalete-de-poche-fabriquee-manuellement_tv
```

The problem is that the video is hidden by Firefox when I use the https version of my blog.

Is this a bug in micawber or, as @raisina mentioned [here](https://github.com/getnikola/nikola/issues/2324#issuecomment-213098524), is it a dailymotion issue?

If it can be of any help, I am currently using:

- nikola 7.7.7
- micawber 0.3.3

[Here](https://github.com/getnikola/nikola/issues/2324) is my original issue

**Comment by coleifer** [comment]
I'm not sure, it sounds to me like it is a Firefox security feature, blocking mixed content maybe? I have no idea, to be honest, but I do not believe this is a bug in micawber.
