### ISSUE TITLE
Django 1.10 support

### ISSUE THREAD

**Issue by pacahon** [coleifer/micawber#70]
Hello! What versions of Django micawber does support?
Now with Django 1.9.x I get `RemovedInDjango110Warning` warnings in log.

```
.../site-packages/django/template/loader.py:97: RemovedInDjango110Warning: render() must be called with a dict, not a Context.
  return template.render(context, request)
```

It's because of `render_to_string` function. I looked through 1.8-1.10 Django docs. Looks like this function really waiting for dict.

**Comment by coleifer** [comment]
Whoa...django is so lame :(
