### ISSUE TITLE
oembed.io does not resolve

### ISSUE THREAD

**Issue by jaap3** [coleifer/micawber#85]
It seems that the oembed.io domain is no longer registered. This means that `bootstrap_oembedio` is dead code for all intents and purposes.

It could possibly be replaced by https://oembed.com/ (https://oembed.com/providers.json)

**Comment by coleifer** [comment]
a0c75787f78e2924801bb8df18ede24dc7d1dd6e

**Comment by coleifer** [comment]
Added a simple "bootstrap_oembed()" helper.
