### ISSUE TITLE
bootstrap_basic raw strings / escapes

### ISSUE THREAD

**Issue by jaap3** [coleifer/micawber#86]
I noticed that a lot of the regular expression patterns in `bootstrap_basic` don't escape dots (match all). This means that a fair number of these patterns will match more than intended.

In addition most patterns aren't marked as raw strings and therefore contain invalid escape sequences. This isn't noticeable directly, but could cause issues in a future python version.

For an example of the latter:

`python -W always -c '"https://\S*?soundcloud.com/\S+"'`
`<string>:1: DeprecationWarning: invalid escape sequence \S`

**Comment by coleifer** [comment]
Yes you are right. This is from me merging patches without reviewing them closely enough. I will fix these regexes.

**Comment by jaap3** [comment]
I can also work on a PR if you'd like. It'll save you some work

**Comment by coleifer** [comment]
Think we should be good to go with the last few commits, but thank you for the offer.

**Comment by coleifer** [comment]
Pushed a new release, 0.4.0
