### ISSUE TITLE
feature request: add media.ccc.de integration

### ISSUE THREAD

**Issue by dvzrv** [coleifer/micawber#87]
Hi!
Falsely [reported to nikola](https://github.com/getnikola/nikola/issues/3253) (to add more features), I'm now reporting this here as a feature request:
It would be great to integrate videos/ streams from https://media.ccc.de into this library.

The service is run by the German hacker association [Chaos Computer Club (CCC)](https://ccc.de), which hosts annual events itself and lends streaming expertise to many external events via its [Video Operation Center (VOC)](https://c3voc.de).

The streaming service is a valuable source of information on many different topics and I think it would be an awesome addition!

If you have pointers on where I can add it (I assume somewhere in [providers.py](https://github.com/coleifer/micawber/blob/master/micawber/providers.py)), I might be able to do a pull request myself. I wouldn't call myself a Python expert though :-)

**Comment by coleifer** [comment]
It needs an oembed endpoint in order for micawber to provide support. https://oembed.com/

Micawber provides oembed integration for python. It's not a general purpose media integration library.

**Comment by dvzrv** [comment]
AFAIK, there is an endpoint for each video (e.g. https://media.ccc.de/v/33c3-7969-shut_up_and_take_my_money/oembed ).

Just to understand this better: If the endpoint is available, but Nikola is unable to make use of this in its specific `.. media::` directive, is this an implementational issue of nikola, micawber, or media.ccc.de?

**Comment by coleifer** [comment]
Hmm, that's interesting... I'll reopen and look into it again. Thanks.

**Comment by dvzrv** [comment]
Well, thank *you*! :-)

**Comment by coleifer** [comment]
I don't see an oembed endpoint however... i.e., that includes metadata or the expected response type. Yeah, you can append "oembed" to the URL and get an HTML player, but I'm not sure that conforms to the oembed spec?
